[bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} â†’ {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"wf2wf/__init__.py" = [
    '__version__ = "{version}"',
] 